target_compile_definitions("${target}" ${public} [==[SIMDJSON_IMPLEMENTATION_FALLBACK=0]==])
target_compile_definitions("${target}" ${public} [==[SIMDJSON_IMPLEMENTATION_WESTMERE=0]==])
target_compile_definitions("${target}" ${public} [==[SIMDJSON_IMPLEMENTATION_HASWELL=0]==])
target_compile_definitions("${target}" ${public} [==[SIMDJSON_IMPLEMENTATION_ICELAKE=0]==])
target_compile_definitions("${target}" ${public} [==[SIMDJSON_IMPLEMENTATION_ARM64=1]==])
target_compile_definitions("${target}" ${public} [==[SIMDJSON_IMPLEMENTATION_PPC64=0]==])
target_compile_definitions("${target}" ${public} [==[SIMDJSON_BUILTIN_IMPLEMENTATION=arm64]==])
target_include_directories("${target}" ${public} [==[$<BUILD_INTERFACE:/Users/yeojun/RecoilEngine/rts/lib/simdjson/include>]==] ${private} [==[$<BUILD_INTERFACE:/Users/yeojun/RecoilEngine/rts/lib/simdjson/src>]==])
target_compile_features("${target}" ${public} [==[cxx_std_11]==])
target_compile_options("${target}" ${private} [==[$<$<CONFIG:DEBUG>:-Og>]==])
